#!/usr/bin/ksh

tmpfile=tmp$$.read.stats

echo nmonfile, hdisks, totalGB, Syscallreads95, Syscallwrites95, FILEread95, FILEwrite95
for file in $*
do
	printf "%s, " $( basename $file | sed 's/\.nmon//' )

	grep ^BBBB, $file |  grep -v ^BBBB,0000 | \
	sed 's/hdisk//' | \
	awk -F, 'BEGIN { sum=0; disks=0; } { sum=sum+$4; disks++; } END { printf("%d,%d", disks, sum)}'

        cat $file | grep ^FILE,T >$tmpfile

        integer RECORDS
        integer PERCENTILE
        RECORDS=`cat $tmpfile | wc -l `
        PERCENTILE=$RECORDS-$RECORDS/20

        cat $tmpfile | awk -F, '{ printf( " %d\n",$6) }' | sort -nr | tail -$PERCENTILE | read readbytes
        cat $tmpfile | awk -F, '{ printf( " %d\n",$7) }' | sort -nr | tail -$PERCENTILE | read writebytes
        
	cat $file | grep ^PROC,T >$tmpfile

        integer RECORDS
        integer PERCENTILE
        RECORDS=`cat $tmpfile | wc -l `
        PERCENTILE=$RECORDS-$RECORDS/20

        cat $tmpfile | awk -F, '{ printf( " %d\n",$7) }' | sort -nr | tail -$PERCENTILE | read reads
        cat $tmpfile | awk -F, '{ printf( " %d\n",$8) }' | sort -nr | tail -$PERCENTILE | read writes

        echo ", "$reads","$writes", "$readbytes","$writebytes

	rm -fr $tmpfile
done
