#!/usr/bin/ksh

#NET,Network I/O p24008prw311,en0-read-KB/s,en1-read-KB/s,en2-read-KB/s,en3-read-KB/s,lo0-read-KB/s,en0-write-KB/s,en1-write-KB/s,en2-write-KB/s,en3-write-KB/s,lo0-write-KB/s
#NET,T0001,0.1,0.0,44.3,0.0,3.5,0.1,0.0,41.5,0.0,3.5


tmpfile=tmp$$.net.stats

echo nmonfile, Networks, readKB95, writeKB95

for file in $*
do
        printf "%s, " $( basename $file | sed 's/\.nmon//' )

	grep ^NET,T $file | \
	awk -F, '{ rsum=0.0; wsum=0.0; for (i = 3; i <= NF; ++i) { if(i<= ((NF-2)/2)+2) rsum +=$i; else wsum +=$i;}  printf("%d,%.1f,%.1f\n", (NF-2)/2, rsum, wsum) }' >$tmpfile

	#
	#awk -F, 'BEGIN { rsum=0.0; wsum=0.0; count=0 }\
        # { rsum=0.0; wsum=0.0; for (i = 3; i <= NF; ++i) { count++; if(i<= ((NF-2)/2)+2) rsum +=$i; else wsum +=$i;}  printf("%d,%.1f,%.1f\n", (NF-2)/2, rsum, wsum) }' >$tmpfile
	#

        integer RECORDS
        integer PERCENTILE
        RECORDS=$(cat $tmpfile | wc -l)
        PERCENTILE=$RECORDS-$RECORDS/20
	readKB=0.0
	writeKB=0.0
        cat $tmpfile | awk -F, '{ printf(" %d\n",$2) }' | sort -nr | tail -$PERCENTILE | read readKB
        cat $tmpfile | awk -F, '{ printf(" %d\n",$3) }' | sort -nr | tail -$PERCENTILE | read writeKB

	head $tmpfile| awk -F, '{ printf(" %d\n",$1) }' | read nets
        
        printf "%d, %.1f,%.1f\n" $nets $readKB $writeKB

	rm -fr $tmpfile
done

